name: Analyze code

on:
  push:
    branches:
      - production

  pull_request:

jobs:
  analyze-code:
    name: Analyze code
    uses: MiguelRipoll23/global/.github/workflows/analyze-code.yml@main

    with:
      node-version: 16
