name: Build package

on:
  push:
    branches-ignore:
      - main

jobs:
  build-package:
    name: Build package
    uses: MiguelRipoll23/global/.github/workflows/build-package.yml@main

    with:
      node-version: 16
