name: Deploy staging

on:
  pull_request:
  pull_request_target:

jobs:
  deploy-package:
    name: Deploy staging
    uses: MiguelRipoll23/global/.github/workflows/deploy-hosting.yml@main
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')

    with:
      node-version: 16
      target-branch: ${{ github.ref }}
      google-cloud-run-host: https://europe-west2-staging-tusestimaciones.cloudfunctions.net/

      # Environment
      environment-id: staging-tusestimaciones
      environment-name: staging

    secrets:
      GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
