name: Deploy Staging

on:
  pull_request:
  pull_request_target:
  workflow_call:
    inputs:
      github-ref:
        required: true
        type: string

jobs:
  deploy-staging:
    name: Build & Deploy
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    uses: ./.github/workflows/deploy-environment.yml
    secrets: inherit
    with:
      github-ref: ${{ inputs.github-ref || github.ref }}
      environment-name: Staging
      artifact-name: staging-pr${{github.event.number}}.zip
      project-name: ${{ vars.WEB_PROJECT_NAME }}
      channel-name: pr${{github.event.number}}
      channel-expiration: "--expires 30d"
      api-base-url: ${{ vars.API_STAGING_BASE_URL }}
