name: Deploy Staging

on:
  pull_request:
  pull_request_target:

jobs:
  deploy-staging:
    name: Deploy Environment
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    uses: ./.github/workflows/deploy-environment.yml
    secrets: inherit
    with:
      environment-name: Staging
      artifact-name: staging-pr${{github.event.number}}.zip
      channel-name: pr${{github.event.number}}
      channel-expiration: "--expires 30d"
      api-base-url: ${{ vars.API_STAGING_BASE_URL }}
