name: Deploy production

on:
  issue_comment:
    types:
      - created

jobs:
  approve-pull-request:
    name: Approve pull request
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/approve')

    steps:
      - name: Approve pull request
        uses: juliangruber/approve-pull-request-action@v1

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}

  deploy-package:
    name: Deploy production
    uses: MiguelRipoll23/global/.github/workflows/deploy-hosting.yml@main
    needs: approve-pull-request

    with:
      node-version: 16
      target-branch: refs/pull/${{ github.event.issue.number }}/merge
      google-cloud-run-host: https://europe-west2-tusestimaciones.cloudfunctions.net/

      # Environment
      environment-id: tusestimaciones
      environment-name: production

    secrets:
      GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

