name: Deploy Staging

on:
  pull_request:
  pull_request_target:
  workflow_call:
    inputs:
      github-ref:
        required: true
        type: string

jobs:
  deploy-staging:
    name: Build & Deploy
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    uses: ./.github/workflows/deploy-environment.yml
    secrets: inherit
    with:
      environment-name: Staging
      artifact-name: staging-pr${{github.event.number}}.zip
      channel-name: pr${{github.event.number}}
      channel-expiration: "--expires 30d"
      github-ref: ${{ inputs.github-ref || github.ref }}
      api-base-url: ${{ vars.API_STAGING_BASE_URL }}

  request-for-review:
    name: Request Review
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{github.event.number}}
          body: "@MiguelRipoll23 ready to review."
