name: Deploy Production

on:
  push:
    branches:
      - production

jobs:
  deploy-production:
    name: Deploy Environment
    uses: ./.github/workflows/deploy-environment.yml
    secrets: inherit
    with:
      environment-name: Production
      artifact-name: production.zip
      channel-name: live
      api-base-url: ${{ vars.API_PRODUCTION_BASE_URL }}
