name: Deploy Production

on:
  push:
    branches:
      - production

  workflow_call:
    inputs:
      github-ref:
        required: true
        type: string

jobs:
  deploy-production:
    name: Build & Deploy
    uses: ./.github/workflows/deploy-environment.yml
    secrets: inherit
    with:
      github-ref: ${{ inputs.github-ref || github.ref }}
      environment-name: Production
      artifact-name: production.zip
      project-name: ${{ vars.WEB_PROJECT_NAME }}
      channel-name: live
      api-base-url: ${{ vars.API_PRODUCTION_BASE_URL }}
